
services:
  web:
    build: .
    container_name: ChatAI_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:12345678@db:5432/chatAI_database

  db:
    image: postgres:15
    container_name: chatAI_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: chatAI_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/script_database.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"

volumes:
  postgres_data:
